:FC-476: :speech_balloon: Update permission table Faas
LivePersonInc/developers-community pull request #1006
Opened 2020-09-29 14:21 UTC by agalagade

2020-09-30 09:56 UTC, LivePersonFaas requested changes

2020-09-30 09:56 UTC, LivePersonFaas commented on pages/Documents/DeveloperTools/LivePersonFunctions/getting-started.md
> +  </tr>
log read is missing

2020-09-30 11:25 UTC, agalagade commented on css/getting-started.css
> +    bottom: 100%;
removed

2020-09-30 11:26 UTC, agalagade commented on pages/Documents/DeveloperTools/LivePersonFunctions/getting-started.md
> +  </tr>
added

2020-09-30 11:26 UTC, agalagade commented on pages/Documents/DeveloperTools/LivePersonFunctions/getting-started.md
> +    </td>
added

2020-09-30 11:26 UTC, agalagade commented on pages/Documents/DeveloperTools/LivePersonFunctions/getting-started.md
> +        <span class="tooltiptext">secret value is obfuscated</span>
updated

2020-10-14 13:07 UTC, merged

2020-10-14 13:07 UTC, lmartliveperson commented
Please verify post merge