:book: improve conversation errors and hook documentaitons
LivePersonInc/developers-community pull request #1058
Opened 2020-10-27 14:57 UTC by akirilyuk

2020-10-29 09:32 UTC, fahimmahmoodmir requested changes
Did you already check with the examples for every vendor of Faas hooks? If not please verify them if they are working otherwise looks good

2020-10-29 09:32 UTC, fahimmahmoodmir commented on pages/Documents/ConversationalAI/Third-PartyBots/bot-conversation-errors.md
> +Double-check you have enough api calls left for Faas. Also please verify that your Faas function is working.
Proposal of description of whole solution heading:

```
Please verify and ensure that you have enough API calls quota left for FaaS function and make sure that FaaS function is working and invokable. Refer to the [Faas Documentation](liveperson-functions-deployment.html#testing-your-function) to understand how to test your function code. 

Furthermore, please ensure your defined function follow the standard implementation as described in Third-Party bots documentation for [Custom Integration](third-party-bots-custom-integration.html). Failure to do so will result in the erroneous result.

```

2020-10-29 09:32 UTC, fahimmahmoodmir commented on pages/Documents/ConversationalAI/Third-PartyBots/bot-conversation-errors.md
> +Provide a response body in the callback, see [Custom Integration Documentation](liveperson-functions-deployment.html#testing-your-function)
`Please make sure to provide a response body in the callback, for further information see`

2020-10-29 10:23 UTC, GFdiablo117 requested changes

2020-10-29 10:23 UTC, GFdiablo117 commented on pages/Documents/ConversationalAI/Third-PartyBots/hook-configuration.md
> +}
I know it's annoying, but could you change it from "input.payload.message" to "payload.message" on this example functions too?

2020-10-29 10:23 UTC, GFdiablo117 commented on pages/Documents/ConversationalAI/Third-PartyBots/hook-configuration.md
> +return callback(null, payload);
input.payload -> payload

2020-10-29 10:23 UTC, GFdiablo117 commented on pages/Documents/ConversationalAI/Third-PartyBots/hook-configuration.md
> +return callback(null, payload);
input.payload -> payload

2020-10-29 10:23 UTC, GFdiablo117 commented on pages/Documents/ConversationalAI/Third-PartyBots/hook-configuration.md
> +return callback(null, payload);
input.payload -> payload

2020-10-29 10:23 UTC, GFdiablo117 commented on pages/Documents/ConversationalAI/Third-PartyBots/hook-configuration.md
> +```
input.payload -> payload

2020-10-29 10:23 UTC, GFdiablo117 commented on pages/Documents/ConversationalAI/Third-PartyBots/hook-configuration.md
> +return callback(null, payload);
input.payload -> payload

2020-10-29 10:23 UTC, GFdiablo117 commented on pages/Documents/ConversationalAI/Third-PartyBots/hook-configuration.md
> +return callback(null, payload);
input.payload -> payload

2020-10-29 10:23 UTC, GFdiablo117 commented on pages/Documents/ConversationalAI/Third-PartyBots/hook-configuration.md
> +}
input.payload -> payload

2020-10-29 10:23 UTC, GFdiablo117 commented on pages/Documents/ConversationalAI/Third-PartyBots/bot-conversation-errors.md
> +Double-check and test the Faas Hook code. You can refer to the [Faas Documentation](liveperson-functions-deployment.html#testing-your-function) to find out how test your function code.
find out how test your function code -> find out how **to** test your function code

2020-10-30 13:07 UTC, fahimmahmoodmir approved these changes
approved from myside

2020-11-09 16:05 UTC, merged