:memo:  Public API Documentation Updates
LivePersonInc/developers-community pull request #1061
Opened 2020-11-04 10:26 UTC by fahimmahmoodmir

- Added the limitation of Public API for commands retentions
- Added the size limitation for Structured Content
- Added the Reblaze limitation for request failure

2020-11-04 10:33 UTC, fahimmahmoodmir commented
Rendering of the Page

![Rendered_Doc](https://user-images.githubusercontent.com/2732245/98100695-84adb580-1e91-11eb-9ff1-13ed9880c8dc.png)

2020-11-04 12:22 UTC, akirilyuk commented on pages/Documents/ConversationalAI/Third-PartyBots/public-api.md
> +    <li>To ensure the safety of the API we are using <a href="https://www.reblaze.com/">Reblaze</a>. if the request throws Security Violation Error (403 - Forbidden) reason could be that your request
why are you using html instead of md?

2020-11-04 12:49 UTC, fahimmahmoodmir commented on pages/Documents/ConversationalAI/Third-PartyBots/public-api.md
> +    <li>To ensure the safety of the API we are using <a href="https://www.reblaze.com/">Reblaze</a>. if the request throws Security Violation Error (403 - Forbidden) reason could be that your request
changed

2020-11-13 11:04 UTC, akirilyuk approved these changes

2020-11-16 12:32 UTC, GFdiablo117 requested changes

2020-11-16 12:32 UTC, GFdiablo117 commented on pages/Documents/ConversationalAI/Third-PartyBots/public-api.md
> +- Our Public API only retains a maximum of last 200 commands **per bot/agent**. There could be the possibility that if a conversation is ongoing but you are not able to fetch the commands because of
Thus, there could be a possibility that an ongoing conversation will not be able to fetch the commands due to this max. commands retention policy.

2020-11-16 12:32 UTC, GFdiablo117 commented on pages/Documents/ConversationalAI/Third-PartyBots/public-api.md
> +- To ensure the safety of the API we are using [Reblaze](https://www.reblaze.com/). if the request throws Security Violation Error (403 - Forbidden) reason could be that your request body contains in
**If** the request throws Security Violation Error (403 - Forbidden) **, the** reason

2020-11-16 13:47 UTC, GFdiablo117 approved these changes

2020-11-18 10:26 UTC, merged