Feature/int 1648 dialogflow v2
LivePersonInc/developers-community pull request #1267
Opened 2021-03-25 16:34 UTC by ahuppert

This addresses INT-1648 as well as INT-1670 (UI rebranding)
Can be published when INT-1670 is ready for deployment

* Rebrands Dialogflow V2 to Dialogflow ES
* Restructures the Documentation for this Vendor with subpages
* Adds information how to get metadata on a consumer message
* Cleanup of images for this vendor
* Remove Dialogflow V1 from the navigation
* ensures the following urls are still reachable
  * third-party-bots-google-dialogflow.html
  * bot-connectors-google-dialogflow-version-2.html

2021-04-16 08:30 UTC, snikic approved these changes

2021-04-26 09:15 UTC, snikic requested changes
fix the merge conflicts

2021-04-29 06:36 UTC, jgonzalezal commented
Looks good to me, just the resolve conflicts

2021-05-03 07:42 UTC, jgonzalezal approved these changes

2021-05-04 11:40 UTC, merged